[paths]
base_path = '.'
results_folder = 'results'
logs_folder = 'logs'
scripts_path = 'scripts'
client_script_path = 'fedt/client.py'
dataset_path = 'ML-EdgeIIoT-FEDT.csv' # [CLASSIF]

[settings]
number_of_jobs = 12
number_of_clients = 10
number_of_rounds = 5
aggregation_strategy = "best_trees"

[settings.sequence]
many_simulations = false
number_of_simulations = 10
aggregation_strategies = ['random', 'best_trees', 'threshold', 'best_forests']

[settings.client]
timeout = 420
debug = true

[settings.server]
IP = "0.0.0.0"
port = "50051"
mcc_threshold = 0.3 # 0.34 # [CLASSIF]
number_of_trees_in_start = 10
increase_of_trees_per_round = 10
validate_dataset_size = 1000
print_every_trees_sent = 50
timeout = 360
debug = true

[dataset]
train_test_split_size = 0.25
percentage_value_of_samples_per_client = 20
label_target = "Attack_type"  # [CLASS]  # opções: "Attack_label", "Attack_type_6", "Attack_type"

[scripts]
network_interface = "eth0"