# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fedt import fedT_pb2 as fedT__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fedT_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FedTStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.aggregate_trees = channel.stream_stream(
                '/fedT.FedT/aggregate_trees',
                request_serializer=fedT__pb2.Forest_CLient.SerializeToString,
                response_deserializer=fedT__pb2.Forest_Server.FromString,
                _registered_method=True)
        self.get_server_model = channel.unary_stream(
                '/fedT.FedT/get_server_model',
                request_serializer=fedT__pb2.Request_Server.SerializeToString,
                response_deserializer=fedT__pb2.Forest_Server.FromString,
                _registered_method=True)
        self.get_server_settings = channel.unary_unary(
                '/fedT.FedT/get_server_settings',
                request_serializer=fedT__pb2.Request_Server.SerializeToString,
                response_deserializer=fedT__pb2.Server_Settings.FromString,
                _registered_method=True)
        self.end_of_transmission = channel.unary_unary(
                '/fedT.FedT/end_of_transmission',
                request_serializer=fedT__pb2.Request_Server.SerializeToString,
                response_deserializer=fedT__pb2.OK.FromString,
                _registered_method=True)


class FedTServicer(object):
    """Missing associated documentation comment in .proto file."""

    def aggregate_trees(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_server_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_server_settings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def end_of_transmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FedTServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'aggregate_trees': grpc.stream_stream_rpc_method_handler(
                    servicer.aggregate_trees,
                    request_deserializer=fedT__pb2.Forest_CLient.FromString,
                    response_serializer=fedT__pb2.Forest_Server.SerializeToString,
            ),
            'get_server_model': grpc.unary_stream_rpc_method_handler(
                    servicer.get_server_model,
                    request_deserializer=fedT__pb2.Request_Server.FromString,
                    response_serializer=fedT__pb2.Forest_Server.SerializeToString,
            ),
            'get_server_settings': grpc.unary_unary_rpc_method_handler(
                    servicer.get_server_settings,
                    request_deserializer=fedT__pb2.Request_Server.FromString,
                    response_serializer=fedT__pb2.Server_Settings.SerializeToString,
            ),
            'end_of_transmission': grpc.unary_unary_rpc_method_handler(
                    servicer.end_of_transmission,
                    request_deserializer=fedT__pb2.Request_Server.FromString,
                    response_serializer=fedT__pb2.OK.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedT.FedT', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedT.FedT', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FedT(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def aggregate_trees(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fedT.FedT/aggregate_trees',
            fedT__pb2.Forest_CLient.SerializeToString,
            fedT__pb2.Forest_Server.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_server_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fedT.FedT/get_server_model',
            fedT__pb2.Request_Server.SerializeToString,
            fedT__pb2.Forest_Server.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_server_settings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedT.FedT/get_server_settings',
            fedT__pb2.Request_Server.SerializeToString,
            fedT__pb2.Server_Settings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def end_of_transmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedT.FedT/end_of_transmission',
            fedT__pb2.Request_Server.SerializeToString,
            fedT__pb2.OK.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
