# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fedT.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fedT.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfedT.proto\x12\x04\x66\x65\x64T\"#\n\x0eRequest_Server\x12\x11\n\tclient_ID\x18\x01 \x01(\x05\"A\n\x0fServer_Settings\x12\x17\n\x0ftrees_by_client\x18\x01 \x01(\x05\x12\x15\n\rcurrent_round\x18\x02 \x01(\x05\";\n\rForest_CLient\x12\x11\n\tclient_ID\x18\x01 \x01(\x05\x12\x17\n\x0fserialised_tree\x18\x02 \x01(\x0c\"(\n\rForest_Server\x12\x17\n\x0fserialised_tree\x18\x01 \x01(\x0c\"\x10\n\x02OK\x12\n\n\x02ok\x18\x01 \x01(\x05\x32\x83\x02\n\x04\x46\x65\x64T\x12?\n\x0f\x61ggregate_trees\x12\x13.fedT.Forest_CLient\x1a\x13.fedT.Forest_Server(\x01\x30\x01\x12?\n\x10get_server_model\x12\x14.fedT.Request_Server\x1a\x13.fedT.Forest_Server0\x01\x12\x42\n\x13get_server_settings\x12\x14.fedT.Request_Server\x1a\x15.fedT.Server_Settings\x12\x35\n\x13\x65nd_of_transmission\x12\x14.fedT.Request_Server\x1a\x08.fedT.OKb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fedT_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST_SERVER']._serialized_start=20
  _globals['_REQUEST_SERVER']._serialized_end=55
  _globals['_SERVER_SETTINGS']._serialized_start=57
  _globals['_SERVER_SETTINGS']._serialized_end=122
  _globals['_FOREST_CLIENT']._serialized_start=124
  _globals['_FOREST_CLIENT']._serialized_end=183
  _globals['_FOREST_SERVER']._serialized_start=185
  _globals['_FOREST_SERVER']._serialized_end=225
  _globals['_OK']._serialized_start=227
  _globals['_OK']._serialized_end=243
  _globals['_FEDT']._serialized_start=246
  _globals['_FEDT']._serialized_end=505
# @@protoc_insertion_point(module_scope)
