"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Request_Server(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: builtins.int
    client_ID: builtins.int
    def __init__(
        self,
        *,
        client_ID: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_ID", b"client_ID"]) -> None: ...

global___Request_Server = Request_Server

@typing.final
class Server_Settings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TREES_BY_CLIENT_FIELD_NUMBER: builtins.int
    CURRENT_ROUND_FIELD_NUMBER: builtins.int
    trees_by_client: builtins.int
    current_round: builtins.int
    def __init__(
        self,
        *,
        trees_by_client: builtins.int = ...,
        current_round: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["current_round", b"current_round", "trees_by_client", b"trees_by_client"]) -> None: ...

global___Server_Settings = Server_Settings

@typing.final
class Forest_CLient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: builtins.int
    SERIALISED_TREE_FIELD_NUMBER: builtins.int
    client_ID: builtins.int
    serialised_tree: builtins.bytes
    def __init__(
        self,
        *,
        client_ID: builtins.int = ...,
        serialised_tree: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_ID", b"client_ID", "serialised_tree", b"serialised_tree"]) -> None: ...

global___Forest_CLient = Forest_CLient

@typing.final
class Forest_Server(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIALISED_TREE_FIELD_NUMBER: builtins.int
    serialised_tree: builtins.bytes
    def __init__(
        self,
        *,
        serialised_tree: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["serialised_tree", b"serialised_tree"]) -> None: ...

global___Forest_Server = Forest_Server

@typing.final
class OK(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.int
    def __init__(
        self,
        *,
        ok: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok"]) -> None: ...

global___OK = OK
