#!/bin/bash

ARQUIVO_PCAP=$1
ARQUIVO_CSV=$2   

# Extraindo: frame.time_epoch ip.src, ip.dst, frame.len

tshark -r "${ARQUIVO_PCAP}" -Y 'tcp' -T fields \
  -E header=y -E separator=, \
  -e frame.time_epoch -e ip.src -e ip.dst -e frame.len \
  > "${ARQUIVO_CSV}"